adb shell pm uninstall --user 0 com.oppoex.afterservice
adb shell pm uninstall --user 0 com.amazon.mShop.android.shopping
adb shell pm uninstall --user 0 com.google.android.marvin.talkback
adb shell pm uninstall --user 0 com.google.android.projection.gearhead
adb shell pm uninstall --user 0 com.heytap.market
adb shell pm uninstall --user 0 com.heytap.quickgame
adb shell pm uninstall --user 0 com.heytap.browser
adb shell pm uninstall --user 0 com.heytap.cloud 
adb shell pm uninstall --user 0 com.heytap.quickgame
adb shell pm uninstall --user 0 com.heytap.datamigration
adb shell pm uninstall --user 0 com.heytap.habit.analysis
adb shell pm uninstall --user 0 com.heytap.market 
adb shell pm uninstall --user 0 com.heytap.mcs 
adb shell pm uninstall --user 0 com.heytap.openid
adb shell pm uninstall --user 0 com.heytap.pictorial
adb shell pm uninstall --user 0 com.heytap.themestore
adb shell pm uninstall --user 0 com.heytap.usercenter
adb shell pm uninstall --user 0 com.heytap.usercenter.overlay
adb shell pm uninstall --user 0 com.google.ar.core
adb shell pm uninstall --user 0 com.realmecomm.app
adb shell pm uninstall --user 0 com.android.mail
adb shell pm uninstall --user 0 com.facebook.appmanager
adb shell pm uninstall --user 0 com.facebook.system
adb shell pm uninstall --user 0 com.facebook.katana
adb shell pm uninstall --user 0 com.facebook.services
adb shell pm uninstall --user 0 com.google.android.youtube
adb shell pm uninstall --user 0 com.google.apps.android.youtube.music
adb shell pm uninstall --user 0 cn.wps.moffice_eng
adb shell pm uninstall --user 0 com.google.android.apps.docs
adb shell pm uninstall --user 0 com.google.android.videos
adb shell pm uninstall --user 0 com.google.android.music
adb shell pm uninstall --user 0 com.google.android.tts
adb shell pm uninstall --user 0 com.google.android.feedback
adb shell pm uninstall --user 0 com.google.android.keep
adb shell pm uninstall --user 0 com.google.android.apps.photos
adb shell pm uninstall --user 0 com.google.android.apps.maps
adb shell pm uninstall --user 0 com.google.android.apps.magazines
adb shell pm uninstall --user 0 com.google.android.apps.nbu.paisa.user
adb shell pm uninstall --user 0 com.google.android.talk
adb shell pm uninstall --user 0 com.google.android.calendar
adb shell pm uninstall --user 0 com.google.android.googlequicksearchbox
adb shell pm uninstall --user 0 com.google.android.marvin.talkback
adb shell pm uninstall --user 0 com.android.wallpaper.livepicker
adb shell pm uninstall --user 0 com.google.android.feedback
adb shell pm uninstall --user 0 com.android.providers.userdictionary
adb shell pm uninstall --user 0 com.coloros.compass2
adb shell pm uninstall --user 0 com.eterno
adb shell pm uninstall --user 0 com.google.android.apps.wellbeing
adb shell pm uninstall --user 0 com.google.android.apps.tachyon
adb shell pm uninstall --user 0 com.nearme.gamecenter
adb shell pm uninstall --user 0 com.coloros.gamespaceui
adb shell pm uninstall --user 0 com.opera.app.news
adb shell pm uninstall --user 0 com.opera.branding.news
adb shell pm uninstall --user 0 com.com.oppo.aod
adb shell pm uninstall --user 0 com.oppo.atlas
adb shell pm uninstall --user 0 com.oppo.bttestmode
adb shell pm uninstall --user 0 com.oppo.criticallog
adb shell pm uninstall --user 0 com.oppo.gmail.overlay
adb shell pm uninstall --user 0 com.oppo.lfeh
adb shell pm uninstall --user 0 com.oppo.logkit
adb shell pm uninstall --user 0 com.oppo.market 
adb shell pm uninstall --user 0 com.oppo.mimosiso
adb shell pm uninstall --user 0 com.oppo.music 
adb shell pm uninstall --user 0 com.oppo.operationManual
adb shell pm uninstall --user 0 com.oppo.ovoicemanager
adb shell pm uninstall --user 0 com.oppo.partnerbrowsercustomizations
adb shell pm uninstall --user 0 com.oppo.qualityprotect
adb shell pm uninstall --user 0 com.oppo.rftoolkit
adb shell pm uninstall --user 0 com.oppo.sos 
adb shell pm uninstall --user 0 com.oppo.startlogkit
adb shell pm uninstall --user 0 com.oppo.usageDump
adb shell pm uninstall --user 0 com.oppo.webview
adb shell pm uninstall --user 0 com.oppo.wifirf
adb shell pm uninstall --user 0 com.oppoex.afterservice
adb shell pm uninstall --user 0 com.oppo.quicksearchbox
adb shell pm uninstall --user 0 com.oppo.ScoreAppMonitor
adb shell pm uninstall --user 0 com.oppo.usercenter
adb shell pm uninstall --user 0 com.oppoex.afterservice
adb shell pm uninstall --user 0 com.coloros.activation
adb shell pm uninstall --user 0 com.coloros.activation.overlay.common
adb shell pm uninstall --user 0 com.coloros.assistantscreen 
adb shell pm uninstall --user 0 com.coloros.athena
adb shell pm uninstall --user 0 com.coloros.avastofferwall
adb shell pm uninstall --user 0 com.coloros.backuprestore
adb shell pm uninstall --user 0 com.coloros.backuprestore.remoteservice
adb shell pm uninstall --user 0 com.coloros.bootreg
adb shell pm uninstall --user 0 com.coloros.childrenspace 
adb shell pm uninstall --user 0 com.coloros.compass2
adb shell pm uninstall --user 0 com.coloros.focusmode 
adb shell pm uninstall --user 0 com.coloros.gamespace 
adb shell pm uninstall --user 0 coloros.gamespaceui 
adb shell pm uninstall --user 0 com.realme.link
adb shell pm uninstall --user 0 com.realmepay.payments
adb shell pm uninstall --user 0 com.realmestore.app
adb shell pm uninstall --user 0 com.coloros.oshare
adb shell pm uninstall --user 0 com.coloros.videoeditor
adb shell pm uninstall --user 0 com.coloros.weather2
adb shell pm uninstall --user 0 com.coloros.weather.service
adb shell pm uninstall --user 0 com.redteamobile.roaming
adb shell pm uninstall --user 0 com.redteamobile.roaming.daemon


