
adb shell pm uninstall --user 0 cn.wps.xioami.abroad.lite
adb shell pm uninstall --user 0 com.amazon.appmanager
adb shell pm uninstall --user 0 com.android.browser
adb shell pm uninstall --user 0 com.cmcm.indianews_for_oem
adb shell pm uninstall --user 0 com.mi.global.shop
adb shell pm uninstall --user 0 com.micredit.in
adb shell pm uninstall --user 0 com.miui.android.fashiongallery
adb shell pm uninstall --user 0 com.newsdog
adb shell pm uninstall --user 0 com.swiftkey.languageprovider
adb shell pm uninstall --user 0 com.swiftkey.swiftkeyconfiguration
adb shell pm uninstall --user 0 com.touchtype.swiftkey
adb shell pm uninstall --user 0 in.amazon.mShop.android.shopping
adb shell pm uninstall --user 0 com.xiaomi.scanner
adb shell pm uninstall --user 0 com.xiaomi.payment
adb shell pm uninstall --user 0 com.xiaomi.miplay_client
adb shell pm uninstall --user 0 com.google.android.tts
adb shell pm uninstall --user 0 com.miui.analytics
adb shell pm uninstall --user 0 com.android.dreams.basic
adb shell pm uninstall --user 0 com.miui.cleanmaster
adb shell pm uninstall --user 0 com.mi.dlabs.vr
adb shell pm uninstall --user 0 com.miui.bugreport
adb shell pm uninstall --user 0 com.xiaomi.joyose
adb shell pm uninstall --user 0 com.miui.msa.global
adb shell pm uninstall --user 0 com.miui.daemon
adb shell pm uninstall --user 0 com.miui.touchassistant
adb shell pm uninstall --user 0 com.miui.screenrecorder
adb shell pm uninstall --user 0 com.android.thememanager
adb shell pm uninstall --user 0 com.miui.analytics
adb shell pm uninstall --user 0 com.miui.miwallpaper
adb shell pm uninstall --user 0 com.miui.translation.kingsoft
adb shell pm uninstall --user 0 com.miui.translation.xmcloud
adb shell pm uninstall --user 0 com.miui.translation.kingsoft
adb shell pm uninstall --user 0 com.miui.translation.youdao
adb shell pm uninstall --user 0 com.miui.translationservice
adb shell pm uninstall --user 0 com.miui.compass
adb shell pm uninstall --user 0 com.google.android.apps.docs
adb shell pm uninstall --user 0 com.google.android.apps.tachyon
adb shell pm uninstall --user 0 com.facebook.services
adb shell pm uninstall --user 0 com.xiaomi.glgm
adb shell pm uninstall --user 0 com.xiaomi.mipicks
adb shell pm uninstall --user 0 com.google.android.googlequicksearchbox
adb shell pm uninstall --user 0 com.google.android.videos
adb shell pm uninstall --user 0 com.google.android.music
adb shell pm uninstall --user 0 com.google.android.tts
adb shell pm uninstall --user 0 com.miui.hybrid.accessory
adb shell pm uninstall --user 0 com.android.mail
adb shell pm uninstall --user 0 com.facebook.appmanager
adb shell pm uninstall --user 0 com.xiaomi.payment
adb shell pm uninstall --user 0 com.mipay.wallet.id
adb shell pm uninstall --user 0 com.mipay.wallet.in
adb shell pm uninstall --user 0 com.xiaomi.miplay_client
adb shell pm uninstall --user 0 com.mi.webkit.core
adb shell pm uninstall --user 0 com.miui.msa.global
adb shell pm uninstall --user 0 com.miui.player
adb shell pm uninstall --user 0 com.miui.global.packageinstaller
adb shell pm uninstall --user 0 com.miui.hybrid
adb shell pm uninstall --user 0 com.xiaomi.midrop
adb shell pm uninstall --user 0 com.xiaomi.discover
adb shell pm uninstall --user 0 com.google.android.marvin.talkback
adb shell pm uninstall --user 0 com.miui.userguide
adb shell pm uninstall --user 0 com.miui.weather2
adb shell pm uninstall --user 0 com.miui.yellowpage
adb shell pm uninstall --user 0 com.mi.dlabs.vr
adb shell pm uninstall --user 0 com.miui.bugreport
adb shell pm uninstall --user 0 com.xiaomi.joyose
adb shell pm uninstall --user 0 com.miui.daemon
adb shell pm uninstall --user 0 com.android.email
adb shell pm uninstall --user 0 com.miui.miservice
adb shell pm uninstall --user 0 com.xiaomi.midrop

